version: '3'
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: UJ93YQBLj8Uggr4dxE267z5sf7xM3AYKWPpoxy5BOkX07B5Gel217bfoZQGYqh27
      MYSQL_DATABASE: diary_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: IfqGtDdgPsUj8TI0Tdgv8ORW9Gug6QgoufllsW0XBak5tdeeqK2F3I8LM85o7ROS
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
