version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy  # Wait for the 'db' service to be healthy
    environment:  # Define environment variables for the Flask container
      DOCKER_CONTAINER: 1
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    healthcheck:
        test: "mariadb ${MYSQL_DATABASE} -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
        interval: 2s
        timeout: 2s
        retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
