version: '3'
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    healthcheck:
        test: "mariadb ${MYSQL_DATABASE} -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
        interval: 2s
        timeout: 2s
        retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
